In [1]:
##################################################################
# This Script:
#    - Gets all 30 mins radar files for one year
#    - Joins them and masks out values over the sea
#    - Gets a 1D array of the data and removes masked out (over the sea
#      values) and np.nan values
##################################################################


##################################################################
# SET UP ENVIRONMENT
##################################################################
import iris.coord_categorisation
import iris
import numpy as np
import os
import geopandas as gpd
import sys
import matplotlib 
import numpy.ma as ma
import warnings
import iris.quickplot as qplt
import iris.plot as iplt
import cartopy.crs as ccrs
from matplotlib import colors
import glob as glob
import datetime
from iris.util import unify_time_units
warnings.simplefilter(action = 'ignore', category = FutureWarning)
from iris.experimental.equalise_cubes import equalise_attributes

# Set up path to root directory
root_fp = "/nfs/a161/gy17m2a/PhD/"
os.chdir(root_fp)

# Create path to files containing functions
sys.path.insert(0, '/nfs/a319/gy17m2a/PhD/Scripts/GlobalFunctions')
from Spatial_plotting_functions import *
from Spatial_geometry_functions import *

resolution = '2.2km'
filtering_name='filtered_100'

gb_gdf = create_gb_outline({'init' :'epsg:3857'})

in_jja=iris.Constraint(time=lambda cell: 6 <= cell.point.month <= 8)

season='wholeyear'

##################################################################
# FOR ONE YEAR AT A TIME
##################################################################
for year in range(2017, 2018):
    print(year)
    filtering_name='filtered_100'
    print(filtering_name)
    # Create directory to store outputs in and get general filename to load files from
    ddir = f"ProcessedData/TimeSeries/NIMROD/30mins/NIMROD_regridded_2.2km/"
    general_filename = f'datadir/NIMROD/30mins/NIMROD_regridded_2.2km/{filtering_name}/AreaWeighted/{year}/*'        
    if not os.path.isdir(ddir):
        os.makedirs(ddir)

    # GET LIST OF ALL FILENAMES FOR THIS YEAR
    filenames =[]
    # Find all files in directory which start with this string
    for filename in glob.glob(general_filename):
        # print(filename)
        filenames.append(filename)
    print(f"loading {len(filenames)} filenames")
    sorted_list = sorted(filenames)

    # LOAD THE DATA
    monthly_cubes_list = iris.load(sorted_list)
    shapes=[]
    for cube  in monthly_cubes_list:
        shapes.append(cube.shape[0])
    print(np.unique(shapes, return_counts=True)[0])
    print(np.unique(shapes, return_counts=True)[1])
    

    filtering_name='unfiltered'
    print(filtering_name)
    # Create directory to store outputs in and get general filename to load files from
    ddir = f"ProcessedData/TimeSeries/NIMROD/30mins/NIMROD_regridded_2.2km/"
    general_filename = f'datadir/NIMROD/30mins/NIMROD_regridded_2.2km/{filtering_name}/AreaWeighted/{year}/*'        
    if not os.path.isdir(ddir):
        os.makedirs(ddir)

    # GET LIST OF ALL FILENAMES FOR THIS YEAR
    filenames =[]
    # Find all files in directory which start with this string
    for filename in glob.glob(general_filename):
        # print(filename)
        filenames.append(filename)
    print(f"loading {len(filenames)} filenames")
    sorted_list = sorted(filenames)
    #sorted_list.remove('datadir/NIMROD/30mins/NIMROD_regridded_2.2km/unfiltered/AreaWeighted/2010/rg_metoffice-c-band-rain-radar_uk_20100302_30mins.nc')

    # LOAD THE DATA
    monthly_cubes_list = iris.load(sorted_list)
    shapes=[]
    for cube  in monthly_cubes_list:
        shapes.append(cube.shape[0])
    print(np.unique(shapes, return_counts=True)[0])
    print(np.unique(shapes, return_counts=True)[1])



2017
filtered_100
loading 365 filenames
[ 2  5 20 22 24 30 31 33 37 39 40 41 42 43 45 46 47 48]
[  1   1   1   1   2   1   1   1   2   2   4   2   1   1   3   2   1 338]
unfiltered
loading 365 filenames


ValueError: list.remove(x): x not in list

In [2]:
# LOAD THE DATA
monthly_cubes_list = iris.load(sorted_list)
shapes=[]
for cube  in monthly_cubes_list:
    shapes.append(cube.shape[0])
print(np.unique(shapes, return_counts=True)[0])
print(np.unique(shapes, return_counts=True)[1])

[ 2  5 20 22 24 30 31 33 37 39 40 41 42 43 45 46 47 48]
[  1   1   1   1   2   1   1   1   2   2   4   2   1   1   3   2   1 338]
