In [2]:
# import gc
# import pickle
# from collections import OrderedDict
# from pyproj import Transformer
import numpy as np
import pandas as pd
pd.set_option('display.float_format', '{:.3f}'.format)
import iris
# import glob
import sys
# import os
# import cartopy.crs as ccrs
# import itertools
# from scipy import spatial
# import numpy.ma as ma
# import tilemapbase
# from math import cos, radians
# import geopandas as gpd
# from shapely.geometry import Polygon
# import matplotlib.pyplot as plt
# from pyproj import Proj, transform
import time

sys.path.insert(1, '../Finding_AMAX_Events')
from Identify_Events_Functions import *
from New_Identify_Events_Functions import *
# from Prepare_Data_Functions import *

home_dir = '/nfs/a319/gy17m2a/PhD/'

em = 'bb198'
yrs_range= '2060_2081'
sample_cube = iris.load(home_dir + f'datadir/UKCP18_every30mins/2.2km_bng/{yrs_range}/{em}/bng_{em}a.pr206101.nc')[0][1,:,:]
tbo_vals = pd.read_csv(home_dir + 'datadir/RainGauge/interarrival_thresholds_CDD_noMissing.txt')

### Read in the 20 year cube

In [3]:
full_timeslice_cube = iris.load(home_dir + 'datadir/Gauge_Timeslices/2060_2081/bb198/gauge0_farFuture.nc')[0]

In [4]:
precip_data = full_timeslice_cube.data
time_coord = full_timeslice_cube.coord('time')

### Compare methods

In [5]:
gauge_num=1
Tb0, idx_2d = find_gauge_Tb0_and_location_in_grid(tbo_vals, gauge_num, sample_cube)

In [16]:
start_time = time.time()
my_events = my_find_independent_events(precip_data, time_coord, Tb0)
my_duration = time.time() - start_time
print(f"My code took {my_duration:.4f} seconds.")

Number of independent rainfall events: 4182
My code took 0.8387 seconds.


In [ ]:
find_top_rainfall_events(my_events, 24)[0]

In [11]:
my_events[0]

(masked_array(data=[1.9924560e-01, 5.2400947e-06, 7.7008735e-08,
                    6.3738565e-07, 1.6437731e-05, 1.7307965e-04,
                    2.8110696e-03, 9.2492159e-03, 1.5851049e-02,
                    1.4960921e-02, 1.6572405e-02, 2.0060657e-02,
                    1.5700243e-01, 8.6431496e-02, 6.7513436e-04,
                    2.1899086e-04, 2.3116058e-02, 5.0247505e-02,
                    4.6311140e-02, 5.3187676e-02, 4.7731578e-02,
                    3.8542092e-02],
              mask=False,
        fill_value=1e+20,
             dtype=float32),
 array([786309.75, 786310.25, 786310.75, 786311.25, 786311.75, 786312.25,
        786312.75, 786313.25, 786313.75, 786314.25, 786314.75, 786315.25,
        786315.75, 786316.25, 786316.75, 786317.25, 786317.75, 786318.25,
        786318.75, 786319.25, 786319.75, 786320.25]))

(156.00789019437315,
 masked_array(data=[4.6330724e+00, 5.7517476e+00, 3.3223553e+01,
                    3.7635204e+01, 2.3975857e+01, 1.7968315e+01,
                    1.5646127e+01, 1.3625112e+01, 2.9598336e+00,
                    1.2119937e-01, 2.0667180e-04, 2.3725879e-06,
                    3.6000577e-07, 1.4569983e-07, 5.6126690e-03,
                    1.7678231e-02, 2.6706414e-06, 1.5192284e-06,
                    2.3894124e-06, 1.2932310e-07, 4.1064050e-06,
                    8.0331665e-07, 1.2967644e-06, 8.2733633e-05,
                    3.0415151e-01, 1.3802987e-01, 4.7243839e-06,
                    1.7150669e-06, 3.2567274e-04, 1.5547168e-03,
                    5.7698129e-05, 4.6260429e-06, 1.5400747e-06,
                    3.3560386e-06, 1.3844015e-04],
              mask=False,
        fill_value=1e+20,
             dtype=float32),
 array([860882.25, 860882.75, 860883.25, 860883.75, 860884.25, 860884.75,
        860885.25, 860885.75, 860886.25, 860886.75, 860887

In [10]:
find_top_rainfall_events(my_events, 4)[0]

(152.45898723602295,
 masked_array(data=[4.6330724e+00, 5.7517476e+00, 3.3223553e+01,
                    3.7635204e+01, 2.3975857e+01, 1.7968315e+01,
                    1.5646127e+01, 1.3625112e+01, 2.9598336e+00,
                    1.2119937e-01, 2.0667180e-04, 2.3725879e-06,
                    3.6000577e-07, 1.4569983e-07, 5.6126690e-03,
                    1.7678231e-02, 2.6706414e-06, 1.5192284e-06,
                    2.3894124e-06, 1.2932310e-07, 4.1064050e-06,
                    8.0331665e-07, 1.2967644e-06, 8.2733633e-05,
                    3.0415151e-01, 1.3802987e-01, 4.7243839e-06,
                    1.7150669e-06, 3.2567274e-04, 1.5547168e-03,
                    5.7698129e-05, 4.6260429e-06, 1.5400747e-06,
                    3.3560386e-06, 1.3844015e-04],
              mask=False,
        fill_value=1e+20,
             dtype=float32),
 array([860882.25, 860882.75, 860883.25, 860883.75, 860884.25, 860884.75,
        860885.25, 860885.75, 860886.25, 860886.75, 860887